"""empty message

Revision ID: 2c12b2dca750
Revises: c57a7d4af9fd
Create Date: 2021-07-27 21:42:31.726526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c12b2dca750'
down_revision = 'c57a7d4af9fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=15), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.drop_table('anstellgut')
    op.drop_table('wasserkefier')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wasserkefier',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('DateTimeKefier', sa.VARCHAR(length=33), nullable=True),
    sa.Column('KefierMenge', sa.INTEGER(), nullable=True),
    sa.Column('WasserMenge', sa.INTEGER(), nullable=True),
    sa.Column('TrockenfruechteMenge', sa.INTEGER(), nullable=True),
    sa.Column('TrockenfruechteArt', sa.VARCHAR(length=200), nullable=True),
    sa.Column('AndereZusaetze', sa.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anstellgut',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('DateTimeAnstellgut', sa.VARCHAR(length=33), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('token')
    # ### end Alembic commands ###
