"""Initial migration

Revision ID: 497fc74754ad
Revises: 
Create Date: 2021-06-07 13:37:56.630356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '497fc74754ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('password', sa.String(length=150), nullable=True),
    sa.Column('first_name', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('wasserkefier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('DateTimeKefier', sa.String(length=33), nullable=True),
    sa.Column('KefierMenge', sa.Integer(), nullable=True),
    sa.Column('WasserMenge', sa.Integer(), nullable=True),
    sa.Column('TrockenfruechteMenge', sa.Integer(), nullable=True),
    sa.Column('TrockenfruechteArt', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wasserkefier')
    op.drop_table('user')
    # ### end Alembic commands ###
