"""empty message

Revision ID: c57a7d4af9fd
Revises: 81e488875077
Create Date: 2021-06-07 23:07:09.600320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c57a7d4af9fd'
down_revision = '81e488875077'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anstellgut',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('DateTimeAnstellgut', sa.String(length=33), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anstellgut')
    # ### end Alembic commands ###
