"""empty message

Revision ID: 81e488875077
Revises: 497fc74754ad
Create Date: 2021-06-07 13:50:00.825585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81e488875077'
down_revision = '497fc74754ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wasserkefier', sa.Column('AndereZusaetze', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wasserkefier', 'AndereZusaetze')
    # ### end Alembic commands ###
